CREATE TABLE AuditLog(
    LogID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    TransactionID NUMBER,
    LogDate DATE,
    Action VARCHAR2(50)
);CREATE OR REPLACE TRIGGER LogTransaction
AFTER INSERT
ON Transactions
FOR EACH ROW
BEGIN
    INSERT INTO AuditLog
    (TransactionID,LogDate,Action)
    VALUES
    (:NEW.TransactionID,SYSDATE,'Transaction Added');
END;
/